'use strict';
// Integration proof for GET /api/chart/snapshot — the genuinely read-only
// public observation endpoint added for external dashboards (app-dashboard).
//
// Proven here against a REAL server + REAL persisted state file:
//   1. At an overdue boundary the endpoint never alters persisted bytes,
//      in-memory store state, generation counters or the chart — no
//      store.update/_persist/catchUp/generation, verified with a _persist
//      spy and byte comparison, not just code reading.
//   2. Chart + nextBoundary come back together from one observation.
//   3. The old endpoints (/api/chart/current, /api/state) are unchanged:
//      they still route through store.update/_persist and still catch up
//      overdue charts when automatic publication is enabled.
//
// Timer note (no incidental writes during the no-write proof): the server's
// 'listening' handler returns before tick()/setInterval when autoCatchUp is
// false (server.js), so the no-write server below has NO timer at all. The
// second server uses a 60s tickMs so its interval cannot fire mid-test; its
// single boot tick is the legitimate publication owner.

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

process.env.TOP40_ADMIN_USER = 'tester';
process.env.TOP40_ADMIN_PASSWORD = 'secret-pass';

const { Store } = require('../src/state');
const { createServer } = require('../server');
const { addHours } = require('../src/dates');
const { catchUp } = require('../src/chart');

const START = '2026-10-03T12:00:00.000Z';

async function boot(t, { automatic = false, tickMs = 60_000 } = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'top40-snapshot-'));
  const store = new Store(path.join(dir, 'state.json'));
  await store.init();
  await store.update(state => { state.originHour = START; });
  let now = new Date('2026-10-03T12:37:42Z');
  const server = createServer({ store, sessionSecret: 'test-only', clock: () => now, autoCatchUp: automatic, tickMs });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => {
    await new Promise(resolve => server.close(resolve));
    await store.queue;
    fs.rmSync(dir, { recursive: true, force: true });
  });
  const base = `http://127.0.0.1:${server.address().port}`;
  async function request(route, { method = 'GET' } = {}) {
    const response = await fetch(base + route, { method });
    return { status: response.status, headers: response.headers, text: await response.text() };
  }
  return { store, request, setNow: value => { now = new Date(value); } };
}

test('snapshot: overdue boundary — zero writes, zero generation, stable single-observation body', async t => {
  const { store, request, setNow } = await boot(t, { automatic: false });

  // No chart published yet: honest null chart, still no writes.
  const empty = await request('/api/chart/snapshot');
  assert.equal(empty.status, 200);
  assert.equal(JSON.parse(empty.text).chart, null);
  assert.equal(JSON.parse(empty.text).nextBoundary, '2026-10-03T13:00:00.000Z');

  // Publish the 12:00 chart through the normal write path (before the spy).
  await store.update(state => catchUp(state, new Date('2026-10-03T12:37:42Z')));
  assert.equal(store.state.lastGeneratedHour, START);

  // Spy on _persist AFTER setup so only request-driven writes are counted.
  const originalPersist = store._persist.bind(store);
  let persistCalls = 0;
  store._persist = async (...args) => { persistCalls += 1; return originalPersist(...args); };

  // Two hours pass with publication stopped: the chart is overdue at 14:37.
  setNow('2026-10-03T14:37:42Z');
  const bytesBefore = fs.readFileSync(store.file, 'utf8');
  const stateBefore = structuredClone(store.state);

  let firstText = null;
  for (let i = 0; i < 5; i++) {
    const res = await request('/api/chart/snapshot');
    assert.equal(res.status, 200);
    assert.equal(res.headers.get('cache-control'), 'no-store');
    assert.ok(!res.text.includes('mojo'), 'snapshot leaks no mojo');
    const body = JSON.parse(res.text);
    // The OLD chart is reported as-is: no generation at the overdue boundary.
    assert.equal(body.chart.hour, START, 'overdue chart observed, never generated by this endpoint');
    assert.ok(Array.isArray(body.chart.entries) && body.chart.entries.length > 0);
    // Chart + next boundary from the same observation, clock-derived.
    assert.equal(body.nextBoundary, '2026-10-03T15:00:00.000Z');
    // No admin/state internals beyond the public projection + boundary.
    assert.deepEqual(Object.keys(body).sort(), ['chart', 'nextBoundary']);
    if (firstText === null) firstText = res.text;
    assert.equal(res.text, firstText, 'repeated reads are byte-identical (no state drift between observations)');
  }

  // The no-write proof: no persist calls, identical file bytes, identical
  // in-memory state, generation cursor untouched.
  assert.equal(persistCalls, 0, 'snapshot never reaches _persist');
  assert.equal(fs.readFileSync(store.file, 'utf8'), bytesBefore, 'persisted bytes unchanged');
  assert.deepEqual(store.state, stateBefore, 'in-memory store state unchanged');
  assert.equal(store.state.lastGeneratedHour, START, 'no generation at the overdue boundary');

  // Old endpoints unchanged: they still route through store.update/_persist…
  const current = await request('/api/chart/current');
  assert.equal(current.status, 200);
  assert.equal(JSON.parse(current.text).chart.hour, START, 'autoCatchUp off: no generation, but write path intact');
  assert.equal(persistCalls, 1, 'old chart endpoint still persists via store.update');
  const state = await request('/api/state');
  assert.equal(state.status, 200);
  assert.equal(JSON.parse(state.text).lastGeneratedHour, START);
  assert.equal(JSON.parse(state.text).nextBoundary, '2026-10-03T15:00:00.000Z');
  assert.equal(persistCalls, 2, 'old state endpoint still persists via store.update');
  assert.equal(fs.readFileSync(store.file, 'utf8'), bytesBefore, 'old endpoints persist identical state bytes');
  assert.deepEqual(store.state, stateBefore);
});

test('snapshot: same public projection as /api/chart/current once the publication owner catches up', async t => {
  const { store, request, setNow } = await boot(t, { automatic: true });

  // The boot tick (publication owner) publishes 12:00; the 60s interval
  // cannot fire during the test. Advance past the boundary so 13:00 is due.
  setNow('2026-10-03T13:37:42Z');

  // Old endpoint UNCHANGED: with automatic publication it still catches up
  // the overdue hour on demand.
  const current = await request('/api/chart/current');
  assert.equal(current.status, 200);
  const currentChart = JSON.parse(current.text).chart;
  assert.equal(currentChart.hour, '2026-10-03T13:00:00.000Z', 'old endpoint still generates overdue charts');
  assert.equal(store.state.lastGeneratedHour, '2026-10-03T13:00:00.000Z');

  // The read-only endpoint observes exactly what was published — same
  // sanitized projection, same boundary basis — and writes nothing itself.
  const snapshot = await request('/api/chart/snapshot');
  assert.equal(snapshot.status, 200);
  const body = JSON.parse(snapshot.text);
  assert.deepEqual(body.chart, currentChart, 'identical public chart projection from one observation');
  assert.equal(body.nextBoundary, '2026-10-03T14:00:00.000Z');
  assert.equal(store.state.lastGeneratedHour, '2026-10-03T13:00:00.000Z', 'snapshot added no generation');
});
